### ISSUE TITLE
Extension to add custom pins and link in pop up

### ISSUE THREAD

**Issue by megalithicportal** [joker-x/Leaflet.geoCSV#10]
Hello, could you help me add a couple of features to the map that are set by columns of data in the CSV file:
1) to use custom pin markers identified in a column in the CSV file
2) to add a custom link in the pop up box loaded from data in the CSV file
I have this (so nearly) working!
Thanks
Andy

**Comment by joker-x** [comment]
@megalithicportal see http://joker-x.github.io/Leaflet.geoCSV/example/icons/index.html

**Comment by megalithicportal** [comment]
Thanks very much!
