### ISSUE TITLE
Customise Popup

### ISSUE THREAD

**Issue by joshdickerson92** [joker-x/Leaflet.geoCSV#13]
I am struggling to be able to customise the popup to only show certain attributes of the CSV and different titles. Using the [Bankias Example](http://joker-x.github.io/Leaflet.geoCSV/example/bankia/index.html) the popup currently uses the script below to pull through all of the attributes using the titles within the CSV.

``` javascript
var popup = '';
		for (var clave in feature.properties) {
			var title = bankias.getPropertyTitle(clave);
			popup += '<b>'+title+'</b><br />'+feature.properties[clave]+'<br /><br />';
		}
		layer.bindPopup(popup);
```

The issue I have is that I cannot change the titles within the CSV as they are exported from a database so I therefore need to manually change them in the script above.

 Using the Bankias example would it be possible to only show the "Localidad" and "Provincia" attributes and change the titles to "locality" and "province" without having to change them in the CSV?

**Comment by joker-x** [comment]
You could access to single field of csv:
```
popup = "Locality: "+ feature.properties[getPropertyName("Localidad")];
```

Also, you could defined an asociation in code, similar to this:
```
var aliases = [
  { alias: "locality", title: "Localidad" },
  { alias: "province", title: "Provincia" }
];

function getAlias(title) {
  result = "";
  aliases.forEach(function(alias) {
    if (alias.title == title) result = alias.alias;
  });
  return result;
}

```
```
...
var popup = '';
popup += "Locality: "+ feature.properties[getPropertyName(getAlias("locality")]+"<br>";
popup += "Locality: "+ feature.properties[getPropertyName(getAlias("province")];
...
```

**Comment by joshdickerson92** [comment]
For both solutions I get:

Uncaught ReferenceError: getPropertyName is not defined

**Comment by joker-x** [comment]
Yes, i forget **bankias.**getPropertyName

**Comment by joshdickerson92** [comment]
Ah yes of course, works perfectly, thanks!

**Comment by joshdickerson92** [comment]
@joker-x Are you aware of a way of the popup showing the attributes of multiple points should they be located in exactly the same place?

**Comment by joker-x** [comment]
It is not implemented, but you can iterate features grouping the same latitude-longitude values in one popup.

**Comment by joshdickerson92** [comment]
Okay thanks, I might have to have a bit more of a look into this, I have explored using clustering which would spiderfy the points at the same location, however this does not appear to work with the popup produced with using geoCSV, not sure if you have come across the same issue?

**Comment by sabatale** [comment]
Works fine with something like:

```
var map = L.map('map').setView([x, y], 12);

$.get('yourdata.csv, function(csvContents) {
  var geoLayer = L.geoCsv(csvContents, {
    firstLineTitles: true,
    fieldSeparator: ','
  });
  //map.addLayer(geoLayer);
  var markers = L.markerClusterGroup();
  markers.addLayer(geoLayer);

  map.addLayer(markers);
});
```
