### ISSUE TITLE
Can this be used with polygons?

### ISSUE THREAD

**Issue by suress** [joker-x/Leaflet.geoCSV#14]
Is there support for drawing polygon using WKT as specified in  GeoCSV specification?

**Comment by joker-x** [comment]
No, this plugin was written before GeoCSV specification, but i would like support in future versions.

**Comment by joker-x** [comment]
I added support of WKT in development branch (POINT, LINESTRING y POLYGON)

@suress can you help me to test it?? https://joker-x.github.io/Leaflet.geoCSV/examples/wkt/
