### ISSUE TITLE
use it with leaflet@1.2.0

### ISSUE THREAD

**Issue by hjoertel** [joker-x/Leaflet.geoCSV#15]
Hi,
did you ever use it with a current version of leaflet and jquery like 3.2.1/?
I'm far from being an a experienced Javascript user, but once, one year ago, I managed to use your code for a private web application together with leaflet.polylineDecorator.js. The latest version of leaflet.polylineDecorator.js requires a current version of leaflet. So  I'm lost.

If you please can test it with the latest software, it will help me with my project. I hope.

Regards
 Heinz

**Comment by joker-x** [comment]
I update examples to Leaflet 1.2, Leaflet.MarkerCluster 1.0.6 and jQuery 3.2.1. Seems to work fine.

**Comment by hjoertel** [comment]
Thank you, Gracias,  Danke

Am 16. August 2017 12:10:55 MESZ schrieb "Iván Eixarch" <notifications@github.com>:
>I update examples to Leaflet 1.2, Leaflet.MarkerCluster 1.0.6 and
>jQuery 3.2.1. Seems to work fine.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/joker-x/Leaflet.geoCSV/issues/15#issuecomment-322726100

-- 
Heinz Jürgen Oertel
vom Android Handy
