### ISSUE TITLE
WKT problems

### ISSUE THREAD

**Issue by soli004** [joker-x/Leaflet.geoCSV#19]
Try using wkt files but I can't get it to work properly. Also seems to only support one title as if you add a new text it fails in the example provided. I would like to import both points and line string and style them based on one of the values. I'm doing a drag and drop function into map to make it easy for users.

This is example of files
`PointCoord;DataVersion;StreetName;StreetNumber;StreetLetter;PostalCode;PostalName
POINT(14.09185 57.76831);JÖNKÖPING;HEDENSTORPSVÄGEN;350;A;55475;JÖNKÖPING
POINT(14.09482 57.76919);JÖNKÖPING;KÄLLEBACKSVÄGEN;310;;55475;JÖNKÖPING
POINT(14.09536 57.76993);JÖNKÖPING;KÄLLEBACKSVÄGEN;293;;55475;JÖNKÖPING`

`Line;DataVersion;ID;altID;Name
LINESTRING(14,094941 57,901929,14,095363 57,901926,14,095364 57,901890,14,095364 57,901890,14,095363 57,901926,14,096189 57,901937,14,096174 57,901892);JÖNKÖPING;10;62;Example`

This is the part of code after drag and drop

`function convertToLayer(CSV) {
	var geoLayer = L.geoCsv(CSV, {
		//titles: ['Feature'],
		//longitudeTitle: 'lng',
		//latitudeTitle: 'lat',
		//lineSeparator: '\n',
		activeWKT: true,
		WKTTitle: 'wkt',
		firstLineTitles: true,
		fieldSeparator: ';',
		onEachFeature: function(feature, layer) {
		 var popupText = '';	
			for(var prop in feature.properties){
				if(feature.properties[prop]){
					popupText += '<b>' + prop + "</b>: "+feature.properties[prop]+"<br>";
		   		}
			}
		layer.bindPopup(popupText, {
		     maxHeight: 128,
		    closeButton: true,
		    className: 'upLoad',
		    offset: L.point(0, -20)
		  });
		layer.on('click', function() {
		    layer.openPopup();
		  });
		},
  		pointToLayer: function (feature, latlng) {
	  		var type = feature.properties.ID
	  		return L.shapeMarker(latlng, {
		  		radius: 5,
		        fillColor: newColorFill(type),
		        fillOpacity: 1,
		        color: newColor(type),
		        weight: 1,
		        shape: 'circle'
		  		})
	  	}
	  	});
      geoLayer.addTo(map);
      map.fitBounds(geoLayer.getBounds());`

**Comment by joker-x** [comment]
I see two mistakes:

In LINESTRING CSV the pairs of coordinates must be coded with a point LINESTRING(14.094941 57.901929,14.095363 57.901926 ...

The WKTTitle option must be match with your title, in your case 'Line' not 'wtk'

**Comment by soli004** [comment]
Yes, thank you missed that! Changed both Linestring and Point to start with 'wkt' (instead of 'PointCoord' and 'Line').
Coordinates now with point, but still nothing on the map...
Would be pretty neat if this could work as its a pain to convert these files to geoJSON and file size will explode
Is it possible to use titles like this and properties values in the end can that be the culprit?
