### ISSUE TITLE
how to remove markers using L.geoCsv

### ISSUE THREAD

**Issue by medy36** [joker-x/Leaflet.geoCSV#6]
Hi,
am using your plug-in to print markers from a CSV. 
i have my markers on the map fine, now i set a filter to filter my CSV  to get lines by Country it works fine except that every time i click on the filter i duplicate the Markers.
 
i need some help please in removing completely the Markers every time i click on my filter.
i found  mapa.removeLayer(arrayOfMarkers);
The arrayOfMarkers is bankias in your example and it's note an array. 
Also i debugged mapa, bankias, cluster to find where markers are store but i didn't find it. 
thanks in advanced,

**Comment by joker-x** [comment]
GeoCSV extends GeoJSON class, so LayerGroup answer can be applied:

  - http://stackoverflow.com/questions/16148598/leaflet-update-geojson-filter
  - http://leafletjs.com/examples/layers-control.html
